name: Cypress

on:
  issue_comment:
    types: [created]

jobs:
  cypress:
    name: Run
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/run-cypress')
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1
