name: Cypress

on:
  issue_comment:
    types: [created]

jobs:
  cypress:
    name: Run
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/run-cypress')
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 4.4.1
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: yarn dev
          wait-on: 'http://localhost:3000'
          record: false
          spec: cypress/integration/*
        env:
          TW_MONGODB_URL: mongodb://localhost:27017
